export const GET_TIMECLINET_REQUEST="GET_TIMECLINET_REQUEST";
export const GET_TIMECLINET_ERROR="GET_TIMECLINET_ERROR";
export const GET_TIMECLINET_SUCCESS="GET_TIMECLINET_SUCCESS";


export const GET_TIMECLINET="GET_TIMECLINET";
export const DELETE_TIMECLINET="DELETE_TIMECLINET";
export const SINGLE_TIMECLINET="SINGLE_TIMECLINET";


export const GET_TIMECLINET_SUCCESS1="GET_TIMECLINET_SUCCESS1"


export const ADD_TIMECLINET_REQUEST='ADD_TIMECLINET_REQUEST';
export const ADD_TIMECLINET_SUCCESS='ADD_TIMECLINET_SUCCESS';
export const ADD_TIMECLINET_FAILURE='GET_TIMECLINET_FAILURE';


export const DELETE_TIMECLINET_SUCCESS="DELETE_TIMECLINET_SUCCESS"
export const DELETE_TIMECLINET_FAILURE="DELETE_TIMECLINET_FAILURE"

export const UPDATE_TIMECLINET_REQUEST='UPDATE_TIMECLINET_REQUEST';
export const UPDATE_TIMECLINET_SUCCESS='UPDATE_TIMECLINET_SUCCESS';
export const UPDATE_TIMECLINET_FAILURE='UPDATE_TIMECLINET_FAILURE';

export const GET_CLINET_SUCCESS="GET_CLINET_SUCCESS"